name: CI

on:
  push:
    branches: [ main, e2e-refactor ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Configure Poetry
        run: poetry config_ virtualenvs.create true

      - name: Install deps
        run: poetry install --no-interaction

      - name: Ruff (formatter check)
        run: poetry run ruff format --check .

      - name: Ruff (lint)
        run: poetry run ruff check .

      - name: Tests
        run: |
          if [ -d tests ]; then poetry run pytest -q; else echo "No tests dir"; fi
