name: release
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write  # para crear tags y releases

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necesario para leer el historial de commits
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry (via pipx)
        run: |
          python -m pip install --upgrade pip pipx
          pipx install poetry
          poetry --version
      - name: Install project deps
        run: poetry install --with dev -E ibkr -E viz -E research -E db -E fast
      - name: Install semantic-release
        run: pipx install python-semantic-release
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish
